get:
  summary: Retrieve user-specific settings.
  responses:
    200:
      description: Settings retrieved successfully.
      content:
        application/json:
          schema:
            $ref: "../components/schemas/UserSettings.yml"
    400:
      description: Bad request. Invalid request format or parameters.
    401:
      description: Unauthorized. Authentication required to view settings.
    404:
      description: Not found. User settings do not exist.
    500:
      description: Internal server error. Something went wrong on the server.

patch:
  summary: Update user-specific settings.
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: "../components/requestBodies/UpdateUserSettingsRequest.yml"
  responses:
    200:
      description: Settings updated successfully.
    400:
      description: Bad request. Invalid request format or missing required fields.
    401:
      description: Unauthorized. Authentication required to update settings.
    404:
      description: Not found. User settings do not exist.
    500:
      description: Internal server error. Something went wrong on the server.
