inputSpec: "./build/devstream.yml"
outputDir: "./build/server/spring"
apiPackage: in.devstream.openapi.api
modelPackage: in.devstream.openapi.model
modelNameSuffix: ""
configPackage: in.devstream.openapi.config
groupId: in.devstream
artifactId: openapi
dateLibrary: java8
serializableModel: true
sortModelPropertiesByRequiredFlag: true
skipDefaultInterface: true
licenseName: GPL-2.0-only
generateBuilders: true
generateConstructorWithAllArgs: true
hideGenerationTimestamp: true
# artifactVersion: 0.0.4
# openApiNullable: false
# disallowAdditionalPropertiesIfNotPresent: false
# hateoas: false
interfaceOnly: true
async: true
# singleContentTypes: true
enumPropertyNaming: "MACRO_CASE"
useJakartaEe: true
useSpringBoot3: true
useSpringController: true
unhandledException: false
useOptional: true
developerEmail: "aditya.mayukh.som@devstream.in"
developerOrganization: "devstream"
developerOrganizationUrl: "https://www.devstream.in"
useTags: true
# apiFirst: true
# delegatePattern: true
