inputSpec: "./build/devstream.yml"
outputDir: "./build/client/typescript"
withoutRuntimeChecks: false
enumPropertyNaming: PascalCase
fileNaming: kebab-case
nullSafeAdditionalProps: true
supportsES6: true
validationAttributes: true
withInterfaces: true