inputSpec: "./build/devstream.yml"
outputDir: "./build/server/spring"
apiPackage: in.devstream.openapi.api
modelPackage: in.devstream.openapi.model
modelNameSuffix: Dto
groupId: in.devstream
artifactId: openapi
dateLibrary: java8
serializableModel: true
artifactVersion: 0.0.2
# openApiNullable: false
# disallowAdditionalPropertiesIfNotPresent: false
# hateoas: false
interfaceOnly: true
# licenseName: Unlicense
# singleContentTypes: true
unhandledException: true
# useTags: true
useOptional: true
  