inputSpec: "./build/devstream.yml"
outputDir: "./build/client/typescript"
withoutRuntimeChecks: false
enumPropertyNaming: PascalCase
fileNaming: kebab-case
nullSafeAdditionalProps: true
supportsES6: true
validationAttributes: true
withInterfaces: true
npmName: "@devstream/client-typescript"
npmVersion: 0.0.1
npmRepository: https://npm.pkg.github.com
repositoryURL: https://www.github.com/AdityaMayukhSom/devstream-openapi
authorName: AdityaMayukhSom