inputSpec: "./build/devstream.yml"
outputDir: "./build/client/typescript"

apiPackage: api
modelPackage: model
withoutRuntimeChecks: false
enumPropertyNaming: PascalCase
fileNaming: PascalCase
nullSafeAdditionalProps: true
supportsES6: true
validationAttributes: true
withInterfaces: false
# prefixParameterInterfaces: true
sagasAndRecords: true
withSeparateModelsAndApi: true
enumPropertyNamingReplaceSpecialChar: true

npmName: "@adityamayukhsom/client-typescript"
# npmVersion: 0.0.4
npmRepository: https://npm.pkg.github.com
repositoryURL: https://www.github.com/AdityaMayukhSom/devstream-openapi

main: ./dist/index.js
types: ./dist/index.d.ts
module: ./dist/esm/index.js
authorName: Aditya Mayukh Som
description: TypeScript Client Stubs for Devstream

templateDir: ./templates/client
files:
  package.json.mustache:
    destinationFilename: package.json
    templateType: SupportingFiles
