name: push files into a remote repository
description: copies files from a build system into another github repository, used to publish docs from one

inputs:
  commit-message:
    type: string
    description: message to be used for committing the files into remote repository
    required: true
  source-directory:
    type: string
    description: path in local directory from which to copy files into the remote repository
    required: true
  target-repository:
    type: stirng
    description: repository in which to put the copied files, for example 'adityamayukhsom/devstream'
    required: true
  target-branch:
    type: string
    description: target repository branch in which to put the copied files
    required: true
  target-directory:
    type: string
    description: directory path in the remote repository in which to put the copied files
    required: true
  bot-token:
    type: string
    description: authentication token required to checkout and publish code to remote repository
    required: true

runs:
  using: "composite"
  steps:
    - name: checkout target repository code
      uses: actions/checkout@v4
      with:
        path: github-target-repository
        repository: ${{ inputs.target-repository }}
        ref: ${{ inputs.target-branch }}
        token: ${{ inputs.bot-token }}
        fetch-depth: 0
        persist-credentials: true

    - name: copy common files to new repo
      shell: bash
      run: |
        mkdir -p github-target-repository/${{ inputs.target-directory }}
        cp -rvT ${{ inputs.source-directory }} github-target-repository/${{ inputs.target-directory }}

    - name: check for new files
      shell: bash
      id: CheckNewFiles
      working-directory: github-target-repository
      run: |
        git add -A
        git status --porcelain | wc -l
        if [[ $(git status --porcelain | wc -l) -gt 0 ]]; then
          echo "TargetHasNewFiles=true" >> "$GITHUB_OUTPUT"
        else
          echo "TargetHasNewFiles=false" >> "$GITHUB_OUTPUT"
        fi

    - name: Setup Node
      shell: bash
      if: ${{ steps.CheckNewFiles.outputs.TargetHasNewFiles == 'true' }}
      working-directory: github-target-repository
      run: |
        git config --global user.name "R2-D2 [bot]"
        git config --global user.email "artoo-detoo@devstream.in"
        git commit -m "docs (bot): ${{ inputs.commit-message }}"
        git push
