name: Complete Publication Workflow

on:
  push:
    branches:
      - release
  workflow_dispatch:

jobs:
  publish-stub-client:
    uses: ./.github/workflows/publish-stub-client.yml
    secrets: inherit

  publish-stub-server:
    uses: ./.github/workflows/publish-stub-server.yml
    secrets: inherit
